import React,{useRef,useState,useEffect} from 'react';
import{createRoot}from'react-dom/client';
import './style.css';
import Works from './Works';
import Navigation from './Navigation';
import About from './About';
import GradientWaves from './DeferredWaves';
import './GradientWaves.css';
import AIVideo from './AIVideo';
// 收到简历后，只需在此更新姓名、联系方式、经历与项目内容。
const profile={name:'侯娇',email:'282695419@qq.com',intro:'以视觉构建感知，以 AI 拓展创意边界。从品牌的第一印象，到每一次具体的视觉表达，探索技术与美感之间的更多可能。'};
const skills=[['01','视觉设计','Visual Design','从构图、字体到色彩，建立具有秩序与辨识度的视觉表达。'],['02','AI 创意探索','AI-powered Creation','将创意方向与生成式工具结合，探索影像、风格和叙事的可能。'],['03','品牌系统思维','Brand Thinking','围绕品牌定位形成统一语言，让不同触点拥有一致的气质。'],['04','跨媒介表达','Across Mediums','在平面、数字界面与动态内容之间，保持创意的一致性。']];
function App(){const video=useRef(null);const[playing,setPlaying]=useState(false);const[ready,setReady]=useState(false);const[notice,setNotice]=useState('');useEffect(()=>{const el=video.current;if(!el)return;let visible=false;const update=()=>{if(!visible||document.hidden)el.pause();else if(!window.matchMedia('(prefers-reduced-motion: reduce)').matches&&!navigator.connection?.saveData){if(!el.getAttribute('src'))el.src='/media/spring-outing.mp4';el.play().catch(()=>{});}};const observer=new IntersectionObserver(([entry])=>{visible=entry.isIntersecting;update()});observer.observe(el);document.addEventListener('visibilitychange',update);return()=>{observer.disconnect();document.removeEventListener('visibilitychange',update)}},[]);const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;return <><div className="page-waves" aria-hidden="true"><GradientWaves horizonColor="#5227FF" waveColor="#FF9FFC" crestColor="#FFFFFF" speed={0.4} amplitude={2.5} waveScale={0.6} waveRatio={0.9} swell={35} turbulence={20} tilt={1.11} zoom={1} height={5.5} fogDepth={15} detail="medium" brightness={1} opacity={1} mouseInteraction={true} parallaxStrength={0.5} grain={true} grainIntensity={0.05}/></div><Navigation name={profile.name}/><main><section className="hero" id="home"><video ref={video} className={ready?'ready':''} autoPlay={!reduced&&!navigator.connection?.saveData} muted loop playsInline preload="none" poster="/media/spring-outing-poster.jpg" onCanPlay={()=>setReady(true)} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} /><div className="shade"/><div className="wrap hero-content"><div className="overline"><b className="dot"/> VISUAL THINKING. HUMAN FEELING.</div><h1>让创意，<br/>超越<span className="outline">所见。</span><i>↗</i></h1><div className="hero-foot"><div><p>视觉设计师 <em>/</em> AI 设计师 <em>/</em> 品牌设计师</p><span>在理性与想象之间，创造有辨识度的表达。</span></div><a href="#projects">探索作品 <b>↓</b></a></div></div><div className="hero-bottom wrap"><span>PERSONAL PORTFOLIO — 2026</span><div>{ready&&!reduced&&<button onClick={()=>{if(playing)video.current.pause();else video.current.play().catch(()=>{})}}>{playing?'Ⅱ 暂停背景视频':'▷ 播放背景视频'}</button>}<span>SCROLL TO DISCOVER</span></div></div></section>
<About/>
<Works/>
<AIVideo/>
<section className="section wrap" id="strengths"><div className="section-top"><span>04 / WHAT I BRING</span><span>从思考，到实现。</span></div><div className="section-heading"><h2>多一种视角，<br/><span>多一种可能。</span></h2><p>把审美、工具与系统思维<br/>放在同一张工作台上。</p></div><div className="skills">{skills.map(([n,t,en,d])=><article key={n}><div className="skill-top"><span>{n}</span><span>↗</span></div><h3>{t}</h3><div className="skill-en">{en}</div><p>{d}</p></article>)}</div></section>
<section className="contact" id="contact"><div className="wrap contact-inner"><div className="section-top"><span>05 / GET IN TOUCH</span><span><b className="dot"/> LET’S CREATE SOMETHING</span></div><div className="contact-main"><div className="overline">一个好的作品，始于一次对话。</div><h2>下一个灵感，<br/>一起<span>实现。</span><i>↗</i></h2><div className="contact-actions"><button onClick={()=>{if(profile.email)window.location.href='mailto:'+profile.email;else setNotice('联系邮箱尚未填写，收到简历后会补充。')}}>聊聊你的想法 <span>↗</span></button><div className="footer-contact-details"><a href="mailto:282695419@qq.com"><span>邮箱</span>282695419@qq.com</a><a href="tel:18042048802"><span>电话</span>18042048802</a><button className="wechat-copy" onClick={async()=>{try{await navigator.clipboard.writeText("houjiao8802");setNotice("微信号已复制：houjiao8802")}catch{setNotice("微信号：houjiao8802，请手动复制")}}}><span>微信</span>houjiao8802</button></div></div><p role="status" className="notice">{notice}</p></div><footer><span>© 2026 {profile.name} · 个人作品集</span><span>VISUAL / AI / BRAND</span><a href="#home">BACK TO TOP ↑</a></footer></div></section></main></>}
createRoot(document.getElementById('root')).render(<App/>);

